{{- $username := required "Git username is required" .Values.username }}
{{- $personalAccessToken := required "Git personal access token is required" .Values.personalAccessToken }}
{{- $host := required "Git host is required" .Values.host }}
{{- $org := required "Git org is required" .Values.org }}
{{- $repo := required "Git repo is required" .Values.repo }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitops-cd-secret.name" . }}
type: Opaque
stringData:
  GITOPS_CD_URL: {{ printf "https://%s:%s@%s/%s/%s.git" $username $personalAccessToken $host $org $repo | quote }}
  GITOPS_CD_BRANCH: {{ .Values.branch | quote }}
